##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-csv
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: https://digitalprojects.brynmawr.edu/ 
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: /art-loan
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-csv

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Circulating Art Loan Collection
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Campus Lending Program at Bryn Mawr College
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Special Collections manages Bryn Mawr College's art collection. As part of the Campus Art Lending Program, we make artwork from the Circulating Art Loan Collection available for display in Administration, Faculty, and Staff offices."
# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords: art; special collections; college campus
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Bryn Mawr College Special Collections

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the CSV file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: artloan_metadata3
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
# page_gen:
#   - data: 'demo-metadata'
#     template: 'item'
#     name: 'objectid'
#     dir: 'items'
#     extension: 'html' 
#     filter: 'objectid'  

##########
# ORGANIZATION SETTINGS
#
# Enter name and link for your organization (replacing the name and links below)
# These values will be used in attribution and data 
organization-name: "Bryn Mawr College Special Collections"
organization-link: https://www.brynmawr.edu/about-college/special-collections
# Add logo image links if you would like them to appear in banner and footer. Delete or leave blank to remove logos.
organization-logo-banner: objects/logo2.png
organization-logo-nav: https://dyzz9obi78pm5.cloudfront.net/app/image/id/674f280c19beadd3b208268d/n/bryn-mawr-logo-left-aligned-reverse-2-color-web.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# Library directory location. This allows you to customize where the standard assets are found.
# provide a relative path in this repository or full url 
lib-assets: /assets/lib
# ignore stuff
exclude: [docs/, Rakefile, rakelib/, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md]
# compress CSS output
sass:
  style: compressed
